/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */

buildscript {
	repositories {
		jcenter()
		mavenCentral()

//        maven {
//            name 'jboss-snapshots'
//            url 'https://repository.jboss.org/nexus/content/repositories/snapshots/'
//        }

        // NUODB: Look locally for our dialect JAR
		mavenLocal()
	}

	dependencies {
	    classpath 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.2'
		classpath 'org.hibernate.build.gradle:hibernate-matrix-testing:3.0.0.Final'
		classpath 'org.hibernate.build.gradle:version-injection-plugin:1.0.0'
		classpath 'gradle.plugin.com.github.lburgazzoli:gradle-karaf-plugin:0.5.1'
		classpath 'org.asciidoctor:asciidoctor-gradle-jvm:3.3.2'
		classpath 'de.thetaphi:forbiddenapis:3.0.1'

        classpath 'org.hibernate.build.gradle:gradle-maven-publish-auth:2.0.1'
        //classpath 'org.hibernate.build.gradle:hibernate-matrix-testing:2.0.0.Final'
        classpath 'org.hibernate.build.gradle:gradle-xjc-plugin:1.0.2.Final'
        classpath 'gradle.plugin.com.github.lburgazzoli:gradle-karaf-plugin:0.1.1'
        //classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.7'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.3'
        //classpath 'de.thetaphi:forbiddenapis:2.5'

        // Force a later version of this JAR, 1.0.2 no longer available
        classpath 'nu.studer:java-ordered-properties:1.0.4'

		// BEGIN: For NUODB V5
		// TODO: Hard coded release for NuoDB JDBC driver, is there better way?
        classpath 'com.nuodb.jdbc:nuodb-jdbc:24.1.0'
		classpath "com.nuodb.hibernate:nuodb-hibernate:${System.getenv('DIALECT_VERSION')}"
		// END
	}
}

plugins {
	id 'me.champeau.buildscan-recipes' version '0.2.3'
	id 'io.github.gradle-nexus.publish-plugin' version '1.1.0'
	id 'nu.studer.credentials' version '2.2'
	id 'org.hibernate.build.xjc' version '2.0.1' apply false
	id 'org.hibernate.build.maven-repo-auth' version '3.0.3' apply false
	id 'biz.aQute.bnd' version '5.1.1' apply false
}

ext {
	sonatypeOssrhUser = project.findProperty( 'SONATYPE_OSSRH_USER' )
	sonatypeOssrhPassword = project.findProperty( 'SONATYPE_OSSRH_PASSWORD' )
}

// BEGIN: For NUODB
// - Search local repo also
// - Check JAR versions and that test database is running

repositories {
	mavenCentral()
    mavenLocal()
}

// Enable debugging comments in the SQL generated by Hibernate
System.setProperty("ENABLE_TRACE_COMMENTS", "true");

// Get and check NuoDB versions, check test database is running.
System.out.println("NuoDB Information");

ext.checker = new CheckNuoDBDatabaseAndVersion();
checker.check();

println("  Checking test database is available")
checker.checkDatabase('gradle/databases.gradle');

// Save these away
ext.nuodbJdbcJarVersion = checker.nuodbJdbcJarVersion;
ext.nuodbHibernateJarVersion = checker.nuodbHibernateJarVersion;
ext.nuodbVersion = checker.nuodbVersion
ext.nuodbDatabaseVersion = checker.nuodbDatabaseVersion
// END: For NUODB

File versionFile = file( "${rootProject.projectDir}/gradle/version.properties" )

ext {
	ormVersionFile = versionFile
	ormVersion = HibernateVersion.fromFile( versionFile, project )

	// Override during releases
	if ( project.hasProperty( 'releaseVersion' ) ) {
		ormVersion = new HibernateVersion( project.releaseVersion, project )
	}

	jpaVersion = new JpaVersion('2.2')
	jakartaJpaVersion = new JpaVersion('3.0.0')

    //nuodbHibernateVersion = new NuodbHibernateVersion();
    //nuodbHibernateJarVersion = System.env['DIALECT_VERSION'] ?: nuodbHibernateVersion.latestVersion;
}

if (!nuodbHibernateJarVersion.endsWith('-hib5'))
    nuodbHibernateJarVersion += '-hib5';

println "    Expecting to use NuoDB Hibernate JAR nuodb-hibernate-${nuodbHibernateJarVersion}.jar"


// The Gradle Nexus Publish Plugin must be applied to the root project and requires group and version

group = 'org.hibernate'
version = project.ormVersion.fullName

nexusPublishing {
	repositories {
		sonatype {
			username = project.sonatypeOssrhUser
			password = project.sonatypeOssrhPassword
		}
	}
}

allprojects {
	repositories {
        // NUODB: Set SONATYPE_VERSION to pull our Jar from there
        if (System.env['SONATYPE_VERSION'] != null) {
            println "hibernate-orm: Using https://oss.sonatype.org/content/repositories/comnuodb-${System.env.SONATYPE_VERSION}/com/nuodb/hibernate/nuodb-hibernate/${nuodbHibernateJarVersion}-hib5/"
            ivy {
                url "https://oss.sonatype.org/content/repositories/comnuodb-${System.env.SONATYPE_VERSION}/"

                layout 'pattern', {
                    artifact '/com/nuodb/hibernate/nuodb-hibernate/${nuodbHibernateJarVersion}-hib5/nuodb-hibernate-${nuodbHibernateJarVersion}-hib5.[ext]'
                }
            }
        }
		mavenCentral()

		//Allow loading additional dependencies from a local path;
		//useful to load JDBC drivers which can not be distributed in public.
		if (System.env['ADDITIONAL_REPO'] != null) {
			flatDir {
				dirs "${System.env.ADDITIONAL_REPO}"
			}
		}
        // NuoDB: Default to adding our dialect explicitly
        else {
            flatDir {
		    	String mvnHome = "${System.properties.get('user.home').replace('\\', '/')}/.m2/repository";
		    	//println "Using default repository: ${mvnHome}"
                dirs "${mvnHome}/com/nuodb/hibernate/nuodb-hibernate/${nuodbHibernateJarVersion}"
            }
        }
        // NUODB: END
    }

	apply plugin: 'idea'

	// minimize changes, at least for now (gradle uses 'build' by default)..
	buildDir = "target"

	group = 'org.hibernate'
	version = project.ormVersion.fullName
}


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Release Task

task release {
	description = "The task performed when we are performing a release build.  Relies on " +
			"the fact that subprojects will appropriately define a release task " +
			"themselves if they have any release-related activities to perform"

	doFirst {
		def javaVersionsInUse = [gradle.ext.javaVersions.main.compiler, gradle.ext.javaVersions.main.release,
								 gradle.ext.javaVersions.test.compiler, gradle.ext.javaVersions.test.release,
								 gradle.ext.javaVersions.test.launcher].toSet()
		// Force to release with JDK 8. It used to not work on JDK11 because of the hibernate-orm-modules module,
		// but this limitation might be resolved now that this module has been deleted?
		if ( javaVersionsInUse != [JavaLanguageVersion.of( 8 )].toSet() ) {
			throw new IllegalStateException( "Please use JDK 8 to perform the release. Currently using: ${javaVersionsInUse}" )
		}
	}
}

task publish {
	description = "The task performed when we want to just publish maven artifacts.  Relies on " +
			"the fact that subprojects will appropriately define a release task " +
			"themselves if they have any release-related activities to perform"
}



// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// CI Build Task

task ciBuild {
	description = "The task performed when one of the 'main' jobs are triggered on the " +
			"CI server.  Just as above, relies on the fact that subprojects will " +
			"appropriately define a release task themselves if they have any tasks " +
			"which should be performed from these CI jobs"
}


wrapper {
	// To upgrade the version of gradle used in the wrapper, run:
	//     ./gradlew wrapper --gradle-version NEW_VERSION
	distributionType = Wrapper.DistributionType.ALL
}


buildScan {
	termsOfServiceUrl = 'https://gradle.com/terms-of-service'
	termsOfServiceAgree = 'yes'
}

buildScanRecipes {
	recipe 'git-commit', baseUrl: 'https://github.com/hibernate/hibernate-orm/tree'
}

class JpaVersion {
	/** The *normal* name (1.0, 2.0, ..) */
	final String name;

	final String osgiName

	JpaVersion(String version){
		this.name = version
		this.osgiName = version + ".0"
	}

	@Override
	String toString() {
		return name
	}
}

class HibernateVersion {
	final String fullName
	final String majorVersion
	final String family

	final String osgiVersion

	final boolean isSnapshot

	HibernateVersion(String fullName, Project project) {
		this.fullName = fullName

		final String[] hibernateVersionComponents = fullName.split( '\\.' )
		this.majorVersion = hibernateVersionComponents[0]
		this.family = hibernateVersionComponents[0] + '.' + hibernateVersionComponents[1]

		this.isSnapshot = fullName.endsWith( '-SNAPSHOT' )

		this.osgiVersion = isSnapshot ? family + '.' + hibernateVersionComponents[2] + '.SNAPSHOT' : fullName
	}

	static HibernateVersion fromFile(File file, Project project){
		def fullName = readVersionProperties(file)
		return new HibernateVersion(fullName, project)
	}

	private static String readVersionProperties(File file) {
		if ( !file.exists() ) {
			throw new GradleException( "Version file $file.canonicalPath does not exists" )
		}
		Properties versionProperties = new Properties()
		file.withInputStream {
			stream -> versionProperties.load( stream )
		}
		return versionProperties.hibernateVersion
	}

	@Override
	String toString() {
		return this.fullName
	}

}

//idea {
//    project {
//		jdkName = gradle.ext.baselineJavaVersion
//		languageLevel = gradle.ext.baselineJavaVersion
//
//		vcs = 'Git'
//    }
//    module {
//        name = "hibernate-orm"
//    }
//}

// NUODB: START
/**
 * Check versions of NuoDB database and associated JARs.
 */
public class CheckNuoDBDatabaseAndVersion {

	/** User home directory */
	public static final String USER_HOME_PROPERTY = "user.home";

	public String nuodbJdbcJarVersion;
	public String nuodbHibernateJarVersion;
	public double nuodbVersion;
	public com.nuodb.hibernate.NuoDBDialectResolutionInfo nuodbDatabaseVersion;

	public void check() {
		String repoPath = System.getenv("ADDITIONAL_REPO");

		if (repoPath == null)
			repoPath = System.getProperty(USER_HOME_PROPERTY) + "/.m2/repository";

		File repoDir = new File(repoPath);

		if (!repoDir.exists() || !repoDir.isDirectory())
			throw new RuntimeException("Repository directory '" + repoDir + "' is not valid");

		File jdbcDir = new File(repoDir, "com/nuodb/jdbc/nuodb-jdbc");
		String nuodbJdbcJarVersion = findInDirectory(jdbcDir, null);
		System.out.println("  NuoDB JDBC JAR version = " + nuodbJdbcJarVersion);
		this.nuodbJdbcJarVersion = nuodbJdbcJarVersion;

		File hibDir = new File(repoDir, "com/nuodb/hibernate/nuodb-hibernate");
		String expectedVersion = System.getenv("DIALECT_VERSION");

		if (expectedVersion == null)
			throw new RuntimeException(
					"DIALECT_VERSION not set in environment (defines current NuoDB Hibernate Driver JAR Version");

		String nuodbHibernateJarVersion = findInDirectory(hibDir, expectedVersion);

		if (!expectedVersion.equals(nuodbHibernateJarVersion))
			throw new RuntimeException(
					"DIALECT_VERSION set to " + expectedVersion + ", but version not found in Maven repo");

		System.out.println("  NuoDB Hibernate JAR version = " + nuodbHibernateJarVersion);
		this.nuodbHibernateJarVersion = nuodbHibernateJarVersion;
	}

	private String findInDirectory(File dir, String expectedVersion) {
		String latest = "";

		for (File versionDir : dir.listFiles()) {
			if (!versionDir.isDirectory())
				continue;

			String version = versionDir.getName();

			if (version.equals(expectedVersion))
				return version;

			if (version.compareTo(latest) > 0)
				latest = version;
		}

		return latest;
	}

	public void checkDatabase(String localDatabasesFilePath) {

		File localDatabasesFile = new File(localDatabasesFilePath);

		if (!localDatabasesFile.exists())
			throw new RuntimeException("No such file " + localDatabasesFile);

		println("  Reading ${localDatabasesFile}")
		java.util.List<String> lines  = new ArrayList<>();
        java.io.BufferedReader rdr = null;

		try {
			rdr = new java.io.BufferedReader(new java.io.FileReader(localDatabasesFile));
			String line;

			while ((line = rdr.readLine()) != null)
			lines.add(line);
		} catch (java.io.IOException e) {
			throw new RuntimeException("Failed to read " + localDatabasesFile + ": " + e.getLocalizedMessage() + " (" + e.getClass().getSimpleName() + ")");
		} finally {
			if (rdr != null) rdr.close();
		}

		java.util.Properties props = new java.util.Properties();
		boolean save = false;

		for (String line : lines) {
			if (!save) {
				if (line.contains("nuodb")) {
					save = true;
				}
				continue;
			}
			else if (line.contains("]"))
				break; // end of nuodb section

			line = line.replace('\'', ' ');

			if (line.endsWith(","))
				line = line.substring(0, line.length() - 1);

			int ix = line.indexOf(':');

			if (ix == -1)
				continue;

			String propName = line.substring(0, ix).trim();
			String propValue = line.substring(ix + 1).trim();
			props.setProperty(propName, propValue);
		}

		String NL = System.lineSeparator();
		String propsString = props.toString();
		propsString = ' ' + propsString.substring(1, propsString.length())
		System.out.println("  JDBC properties: " + NL + '   ' + propsString.replaceAll(",", NL + '   ') + NL);

		// Build a database URL.  We need the database name and any connection properties
		String url = props.getProperty("jdbc.url");
		int ix = url.lastIndexOf("/");
		url = "jdbc:com.nuodb://localhost" + url.substring(ix);
		//System.out.println("url = " + url);

		java.util.Properties dbProps = new java.util.Properties();
		dbProps.setProperty("url", url);
		dbProps.setProperty("user", props.getProperty("jdbc.user"));
		dbProps.setProperty("password", props.getProperty("jdbc.pass"));
		//System.out.println(dbProps);
		javax.sql.DataSource dataSource = new com.nuodb.jdbc.DataSource(dbProps);

		try {
			Object nuodbDatabaseVersion = new com.nuodb.hibernate.NuoDBDialectResolutionInfo(dataSource);
			System.out.println("  Connected to database URL: " + url);

			// Database version info
			this.nuodbVersion = nuodbDatabaseVersion.getDatabaseVersionNumber();
			this.nuodbDatabaseVersion = nuodbDatabaseVersion;
			System.out.println("    NuoDB version " + nuodbDatabaseVersion + " is available (" + nuodbVersion + ')');
		} catch (Exception e) {
			String start = "\033[31;107m";
			String end = "\033[m";

			throw new RuntimeException( 
				   start + NL + "  ERROR: Failed to connect to a database - is it running? "
			        + NL + "    URL: " + url
					+ NL + "   INFO: " + e.getLocalizedMessage() + " (" + e.getClass().getSimpleName() + ")"
					+ end);
		}
	}
}
// // NUODB: END