/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id "local.publishing-java-module"
    id "local.publishing-group-relocation"

    id "org.hibernate.orm.antlr"
    id "local-xjc-plugin"
}

description = 'Hibernate\'s core ORM functionality'

configurations {
    tests {
        description = 'Configuration for the produced test jar'
    }
}

// BEGIN: For NUODB - search local repo also
repositories {
	mavenCentral()
    mavenLocal()
}

// Does the NuoDB JDBC JAR support NClob, NString ... ?
if (nuodbJdbcJarVersion.toString().compareTo("24.2.2") < 0)
    println("Skipping NClob tests - wrong NuoDB JDBC JAR version: ${nuodbJdbcJarVersion}");
else
    println("Skipping NClob tests - compliant NuoDB JDBC JAR version: ${nuodbJdbcJarVersion}");

// --------------------------------------------------------------------- //
// -          Control which tests are included or excluded 6.6         - //
// --------------------------------------------------------------------- //

test {
    filter {
        // --------------------------------------------
        // Tests modified for NuoDB differences
        // --------------------------------------------
        // org.hibernate.orm.test.query.hql.StandardFunctionTests

        // ---------------------------------------------------------------------
        // Failing tests that need fixing?
        // ---------------------------------------------------------------------

        // NuoDB has a slightly different error message
        // org.hibernate.orm.test.batch.BatchOptimisticLockingTest.testBatchAndOptimisticLocking

        // Contrived LIKE patterns fail (3 tests)
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.LikeEscapeDefaultTest'

        // Works when run on its own
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testAggregateIndexElementWithPath'
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testDurationArithmetic'
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testDurationArithmeticWithParameters'
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testFormat'
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testFormatTime'
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testImplicitCollectionJoinInSelect'
        excludeTestsMatching 'org.hibernate.orm.test.hql.BulkManipulationTest.testInsertWithManyToOne' // Undefined reference to DESCRIPTION
        excludeTestsMatching 'org.hibernate.orm.test.hql.BulkManipulationTest.testInsertWithSelectListUsingJoins'

        // WARNING: Failing tests from this class leak connections and exhaust the pool, so all subsequent tests fail
        excludeTestsMatching 'org.hibernate.orm.test.hql.ASTParserLoadingTest.testEJBQLFunctions' // Cannot compare INTEGER to OBJECT?
        //includeTestsMatching 'ASTParserLoadingTest.testAnyMappingReference'
        //includeTestsMatching 'ASTParserLoadingTest.testComponentParameterBinding'
        //includeTestsMatching 'ASTParserLoadingTest.testComponentQueries'
        //includeTestsMatching 'ASTParserLoadingTest.testRowValueConstructorSyntaxInInList'

        // Not sure what this should be showing, but it exposed a strange behavior where Hibernate generates: SELECT .... GROUP BY ().
        //includeTestsMatching 'CriteriaLiteralWithSingleQuoteTest.testLiteralProjectionAndGroupBy'

        // undefined reference to "V1_0"."NAME", presumably because 'v1_'0' is only valid within the join in brackets
        // select  li1_0.id, li1_0.order_id, li1_0.product_id, li1_0.quantity, li1_0.subTotal  from  LineItem li1_0
        //     join (Product p1_0 join Vendor v1_0 on v1_0.id=p1_0.vendor_id) 
        //        on p1_0.id=li1_0.product_id , /* CROSS JOIN */ orders o1_0 join ASSOCIATE sa1_0 
        //        on sa1_0.id=o1_0.associate_id  and v1_0.name=sa1_0.familyName;
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.JpaCrossJoinBaselineTests.testCrossJoin'

        // Timezones and timestamps. Several of these fail even though expected and actual match
        excludeTestsMatching 'org.hibernate.orm.test.type.LocalDateTest.nativeWriteThenRead'
        excludeTestsMatching 'org.hibernate.orm.test.type.LocalDateTest.writeThenNativeRead'
        excludeTestsMatching 'org.hibernate.orm.test.type.LocalDateTest.nativeWriteThenRead'
        excludeTestsMatching 'org.hibernate.orm.test.type.LocalDateTest.writeThenRead'
   
        // Timezone not picked up from Hibernate
        excludeTestsMatching 'org.hibernate.orm.test.timestamp.JdbcTimeCustomTimeZoneTest.testTimeZone'
        excludeTestsMatching 'org.hibernate.orm.test.timestamp.JdbcTimestampCustomSessionLevelTimeZoneTest.testTimeZone'
        excludeTestsMatching 'org.hibernate.orm.test.timestamp.JdbcTimestampCustomTimeZoneTest.testTimeZone'

        // Can't convert LocalDate, LocalTime, LocalDateTime to column type
		excludeTestsMatching 'GlobalJavaTimeJdbcTypeTests.testLocalDate'
		excludeTestsMatching 'GlobalJavaTimeJdbcTypeTests.testLocalDateTime'
		excludeTestsMatching 'GlobalJavaTimeJdbcTypeTests.testLocalTime'
		excludeTestsMatching 'JavaTimeJdbcTypeTests.testLocalDate'
		excludeTestsMatching 'JavaTimeJdbcTypeTests.testLocalDateTime'
		excludeTestsMatching 'JavaTimeJdbcTypeTests.testLocalTime'

        // Test breaks Hibernate's SQL generator
        //excludeTestsMatching 'org.hibernate.orm.test.query.hql.set.SetOperationTest.testAlternatingSetOperator' // No such element exception

        // Sequence failing
        // includeTestsMatching 'org.hibernate.orm.test.secondarytable.HHH18813Test' 
        // includeTestsMatching 'org.hibernate.orm.test.secondarytable.SecondaryRowTest' 
        // includeTestsMatching 'org.hibernate.orm.test.id.enhanced.*'
        // includeTestsMatching 'org.hibernate.orm.test.id.sequence.*'
        // includeTestsMatching 'org.hibernate.orm.test.schemaupdate.idgenerator.SequenceGeneratorIncrementTest.*'
        // includeTestsMatching 'org.hibernate.orm.test.batch.BatchSelectAndForceIncrementVersionTest.testBatchOptimisticForceIncrement'
        // includeTestsMatching 'org.hibernate.orm.test.batch.BatchSelectAndForceIncrementVersionTest.testBatchPessimisticForceIncrement'
		// includeTestsMatching 'SequenceInformationTest.test'
		// includeTestsMatching 'SequenceGeneratorTest.testStartOfSequence'
		// includeTestsMatching 'SequenceMismatchStrategyFixWithSequenceGeneratorTest.test'
		// includeTestsMatching 'SequenceMismatchStrategyDefaultExceptionTest.test'
		// includeTestsMatching 'SequenceMismatchStrategyExceptionEnumTest.test'
		// includeTestsMatching 'SequenceMismatchStrategyLogTest.test'

        //excludeTestsMatching 'org.hibernate.orm.test.bootstrap.scanning.PackagedEntityManagerTest' // Can't find persistence.xml files
        //excludeTestsMatching 'org.hibernate.orm.test.bootstrap.scanning.ScannerTest' // Can't find orm.xml files

        //includeTestsMatching 'org.hibernate.orm.test.filter.DynamicFilterTest.testFiltersOnMultiTableHqlDelete' // Undefined reference in DELETE
        //includeTestsMatching 'org.hibernate.orm.test.filter.DynamicFilterTest.testFiltersOnSimpleHqlDelete' // Undefined reference in DELETE

        // Why do these query tests fail?
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testColumnFunction' // Expected: <the string> but was: <null> 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testImplicitCollectionJoinInSelects' // Expected: (a collection containing <0> and a collection containing <1>)  but: a collection containing <0> 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testMaxGreatest' // Expected: <10> but was: <null> 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testTupleInSubqueryResult' // Expected: <[true]> but was: <[false]> 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testAggregateIndexElementKeyValueWithAlias' // No result found for query [select max(index(l)) from EntityOfLists eol join eol.listOfNumbers l group by eol] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testAggregateIndicesElementsWithPath' // NoReult No result found for query [select max(indices(eol.listOfNumbers)) from EntityOfLists eol] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testGroupByGroupingSets' // SQLGrammar JDBC exception executing SQL [select avg(eob1_0.the_double),eob1_0.gender,eob1_0.the_int from EntityOfBasics eob1_0 group by cube(eob1_0.gender,eob1_0.the_int)] [can't find function "CUBE"] [n/a] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testGroupByRollup' //SQLGrammar JDBC exception executing SQL [select avg(eob1_0.the_double),eob1_0.gender,eob1_0.the_int from EntityOfBasics eob1_0 group by rollup(eob1_0.gender,eob1_0.the_int)] [can't find function "ROLLUP"] [n/a] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testHyperbolic' // No result found for query [select sinh(e.theDouble) from EntityOfBasics e] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testImplicitCollectionJoinInSelectAggregate' // No result found for query [select max(index(eol.listOfNumbers)) from EntityOfLists eol group by eol] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testImplicitCollectionJoinInWhere' // No result found for query [from EntityOfLists eol join eol.listOfOneToMany se where element(se).someLong=5] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testKeyIndexValueEntry' // No result found for query [select index(l) from EntityOfLists eol join eol.listOfBasics l] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testMaxOverUnion' // SQLGrammar exception, expected end of statement got parenthesis
                                       // select max(derived1_0.val) from (select se1_0.someLong from SIMPLE_ENTITY se1_0 union select se2_0.someInteger from SIMPLE_ENTITY se2_0) derived1_0^(val) 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testMaxindexMaxelement' // NoResult No result found for query [select maxindex(eol.listOfBasics) from EntityOfLists eol] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testMoreIntervalDiffExpressions' // GenericJDBC JDBC exception executing SQL [select (DATE_ADD(CURRENT_TIMESTAMP, INTERVAL round(-(1000 * DATEDIFF(MICROSECOND /* No native using MICROSECOND*1000 */, {ts '1990-01-01 12:30:00.000000000'}, CURRENT_TIMESTAMP))/1000) MICROSECOND /* native unsupported */)) FROM Dual] [Too big interval -1113990001941297] [Too big interval -1113990001941297] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testOverlayFunction' // IndexOutOfBounds Index 0 out of bounds for length 0 


        // --------------------------------------------
        // Tests to skip due to known NuoDB limitations
        // --------------------------------------------

        // Does the NuoDB JDBC JAR support NClob, NString ... ?
        if (nuodbJdbcJarVersion.compareTo("24.2.2") >= 0) {
            excludeTestsMatching 'NClobTest.test'
            excludeTestsMatching 'org.hibernate.orm.test.type.LobUnfetchedPropertyTest.testNClob'
        } 

        if (nuodbDatabaseVersion.isBefore("7.0.0")) {
            // FULL OUTER JOIN not supported until NuoDB 7
            excludeTestsMatching 'EntityJoinWithJoinedInheritanceTest.testFullJoin'
            excludeTestsMatching 'EntityJoinWithSingleTableInheritanceTest.testFullJoin'
            excludeTestsMatching 'EntityJoinWithTablePerClassInheritanceTest.testFullJoin'
            excludeTestsMatching 'org.hibernate.orm.test.join.OuterJoinTest.testJoinOrderWithFullJoin'
            excludeTestsMatching 'org.hibernate.orm.test.join.OuterJoinTest.testJoinOrderWithFullJoinWithIdDereference'
            excludeTestsMatching 'org.hibernate.orm.test.join.OuterJoinTest.testJoinOrderWithFullNormalJoin'
            excludeTestsMatching 'org.hibernate.orm.test.join.OuterJoinTest.testJoinOrderWithFullNormalJoinWithIdDereference'
            excludeTestsMatching 'org.hibernate.orm.test.mapping.inheritance.joined.JoinedSubclassTest.testJoinedSubclass'
            excludeTestsMatching 'org.hibernate.orm.test.inheritance.join.AttributeJoinWith*.testFullJoin'
            excludeTestsMatching 'org.hibernate.orm.test.query.RightJoinNullnessPredicateQueryTest.testDereferenceIsNull'
            excludeTestsMatching 'org.hibernate.orm.test.query.RightJoinNullnessPredicateQueryTest.testFullJoinIsNull'
            excludeTestsMatching 'org.hibernate.orm.test.query.SelectForeignKeyWithMissingFromTest.testFullJoin'
            excludeTestsMatching 'org.hibernate.orm.test.query.SelectForeignKeyWithMissingFromTest.testFullJoinEntityPath'

            // Not until NuoDB 7 for window functions var_samp(), rank() ...
            excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testStatisticalFunctions'
            excludeTestsMatching 'org.hibernate.orm.test.hql.HQLTest.test_var_function_example'
            excludeTestsMatching 'org.hibernate.orm.test.query.criteria.CriteriaWindowFunctionTest.testRank'
            excludeTestsMatching 'org.hibernate.orm.test.query.hql.WindowFunctionTest.testOrderByAndAlias'
            excludeTestsMatching 'org.hibernate.orm.test.query.hql.WindowFunctionTest.testRank'
            excludeTestsMatching 'org.hibernate.orm.test.jpa.query.CorrelationCteDerivedRootTest.tesDerivedRoot'
		    excludeTestsMatching 'org.hibernate.orm.test.query.hql.InsertSelectTests.testInsertSelectDistinct'

            // INTERSECT and EXCEPT 
            excludeTestsMatching 'org.hibernate.orm.test.bootstrap.binding.annotations.embedded.EmbeddedTest.testQueryWithEmbeddedParameterAllNull'
            excludeTestsMatching 'org.hibernate.orm.test.bootstrap.binding.annotations.embedded.EmbeddedTest.testQueryWithEmbeddedParameterOneNull'
		    excludeTestsMatching 'org.hibernate.orm.test.hql.HQLTest.test_hql_derived_join_example'

		    excludeTestsMatching 'CriteriaQualifiedJoinTest.testJoinLateral'   // emulation -> unsupported SQL construct

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromEmbeddedIdTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromEmbeddedIdTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromEmbeddedIdTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromIdClassTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromIdClassTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromIdClassTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromInverseOneEmbeddedIdTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromInverseOneEmbeddedIdTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromInverseOneEmbeddedIdTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromInverseOneIdClassTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromInverseOneIdClassTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromInverseOneIdClassTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromInverseOneTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromInverseOneTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromInverseOneTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromManyToManyEmbeddedIdTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromManyToManyEmbeddedIdTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromManyToManyEmbeddedIdTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromManyToManyIdClassTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromManyToManyIdClassTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromManyToManyIdClassTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromManyToManyTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromManyToManyTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromManyToManyTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromOneToManyEmbeddedIdTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromOneToManyEmbeddedIdTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromOneToManyEmbeddedIdTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromOneToManyIdClassTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromOneToManyIdClassTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromOneToManyIdClassTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromOneToManyTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromOneToManyTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromOneToManyTests.testEntityJoin'

            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromTests.testBasic'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromTests.testEmbedded'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromTests.testEntity'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromTests.testEntityImplicit'
            excludeTestsMatching 'org.hibernate.orm.test.query.SubQueryInFromTests.testEntityJoin'

            // CASE ... IN (...) weirdness
            excludeTestsMatching 'org.hibernate.orm.test.hql.HQLTest.test_hql_in_predicate_example_1'
            excludeTestsMatching 'org.hibernate.orm.test.jpa.ql.TreatKeywordTest.testFilteringJoinedSubclasses'
        }

        if (nuodbDatabaseVersion.isBefore("7.0.2")) {
            // JIRA DB-40465: Can't create table with HELPER_TYPE column. FIXED in 7.0.2
            excludeTestsMatching 'IdClassPredicateTest.testCountIdClassAttributes'
            excludeTestsMatching 'IdClassPredicateTest.testDeclaredIdClassAttributes'
            excludeTestsMatching 'IdClassPredicateTest.testSupertypeIdClassAttributes'

            // JIRA DB-40458: CASE statement weirdness cast(? AS VARCHAR (2147483647)). FIXED in 7.0.2
		    excludeTestsMatching 'org.hibernate.orm.test.query.hql.CaseStatementTest.testSearchedCaseStatementWithAllParamResults'
        }

        // WEEK not implememted for extract()
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testExtractFunctionWeek'
        //includeTestsMatching 'org.hibernate.orm.test.query.hql.StandardFunctionTests.testExtractFunction' // test modified to skip WEEK Tests 
	    //includeTestsMatching 'org.hibernate.orm.test.query.hql.StandardFunctionTests.testExtractFunctionWithAssertions' // test modified to skip WEEK Tests 

        // Row number with 'ties' not supported. Requires dense_rank() apparently, but still fails
        excludeTestsMatching 'FetchClausePaginationTest.testFetchWithTies'

        // NuoDB quietly casts a boolean to a string, so the code runs without the expected exception
        // Most databases do this and also exclude these tests
        excludeTestsMatching 'org.hibernate.orm.test.filter.FilterParameterTests.testYesNoMismatch'
        excludeTestsMatching 'org.hibernate.orm.test.filter.FilterParameterTests.testNumericMismatch'

        // No support for first_value, nth_value, percent_rank, cume_dist()
		excludeTestsMatching 'CriteriaWindowFunctionTest.testFrame'
		excludeTestsMatching 'CriteriaWindowFunctionTest.testFirstValue'
		excludeTestsMatching 'CriteriaWindowFunctionTest.testReusableWindow'
		excludeTestsMatching 'CriteriaWindowFunctionTest.testNthValue'
        excludeTestsMatching 'WindowFunctionTest.testFrame'

        // NuoDB requires ORDER BY with some window-functions
		excludeTestsMatching 'CriteriaWindowFunctionTest.testRowNumberWithoutOrder'
		excludeTestsMatching 'CriteriaTimeoutTest.testCreateMutationQueryCriteriaInsertSelect'
        excludeTestsMatching 'WindowFunctionTest.testRowNumberWithoutOrder'
		excludeTestsMatching 'org.hibernate.orm.test.query.criteria.InsertSelectTests.simpleTest'

        // Table and column names must be unique. Even if quoted, "Table1" and "TABLE1" are considered the same.
        excludeTestsMatching 'org.hibernate.orm.test.schemaupdate.SchemaUpdateTest'

        // sign() function in @Formula annotation is used as-is - the registered emulation is ignored
        //excludeTestsMatching 'FormulaWithPartitionByTest'

        // TIMESTAMP precision is always 6 (MICROSECONDS)
        excludeTestsMatching 'org.hibernate.orm.test.temporal.FractionalSecondsTests.testUsage0'  // Expects precision(0)
        excludeTestsMatching 'org.hibernate.orm.test.temporal.FractionalSecondsTests.testUsage3'  // Expects precision(3)
        //excludeTestsMatching 'org.hibernate.orm.test.temporal.FractionalSecondsTests.testUsage9'
        excludeTestsMatching 'org.hibernate.orm.test.temporal.JavaTimeFractionalSecondsTests.testUsage0'  // Expects precision(0)
        excludeTestsMatching 'org.hibernate.orm.test.temporal.JavaTimeFractionalSecondsTests.testUsage3'  // Expects precision(3)
        //excludeTestsMatching 'org.hibernate.orm.test.temporal.JavaTimeFractionalSecondsTests.testUsage9'

        // CASCADE DELETE not supported
        excludeTestsMatching 'ManyToManyBidirectionalTest.testRemoveMappedBySide'
    	excludeTestsMatching 'ToOneOnDeleteTest.testManyToOne'

        // Dependent Right Outer Join not supported even in 7
        excludeTestsMatching 'org.hibernate.orm.test.join.OuterJoinTest.testJoinOrderWithRightJoinWithInnerImplicitJoins'
        //excludeTestsMatching 'org.hibernate.orm.test.join.OuterJoinTest.testJoinOrderWithFullJoin'

        // No support for UPDATE ... ON CONFLICT
        excludeTestsMatching 'InsertConflictTests'

        // Type implementation mismatches
        excludeTestsMatching 'org.hibernate.orm.test.jpa.query.NativeQueryResultTypeAutoDiscoveryTest.tinyintType'  // No support for the tinyint datatype so we use smallint
        excludeTestsMatching 'org.hibernate.orm.test.jpa.query.NativeQueryResultTypeAutoDiscoveryTest.floatType'  // Stores all floating point numbers as double, never returns a float
        excludeTestsMatching 'org.hibernate.orm.test.jpa.query.NativeQueryResultTypeAutoDiscoveryTest.realType'  // Stores all floating point numbers as double, never returns a float
        excludeTestsMatching 'org.hibernate.orm.test.jpa.query.NativeQueryResultTypeAutoDiscoveryTest.numericType'  // Value is too big for the maximum allowed precision of NuoDB
        excludeTestsMatching 'org.hibernate.orm.test.jpa.query.NativeQueryResultTypeAutoDiscoveryTest.decimalType'  // Value is too big for the maximum allowed precision of NuoDB
        excludeTestsMatching 'org.hibernate.orm.test.jpa.query.NativeQueryResultTypeAutoDiscoveryTest.binaryTypes'  // NuoDB maps BINARY and VARBINARY to BLOB
        excludeTestsMatching 'org.hibernate.orm.test.jpa.query.NativeQueryResultTypeAutoDiscoveryTest.longBinaryType'  // NuoDB maps LONGVARCHAR to BLOB

        // JIRA DB-37128: NuoDB Byte cannot be set to a negative value using a PreparedStatement. OPEN
        excludeTestsMatching 'ByteTest.testByteDataPersistenceAndRetrieval'

        // NuoDB has no UUID type
		excludeTestsMatching 'org.hibernate.orm.test.tenantidpk.TenantPkTest'

        // NuoDB requires ORDER BY whenever GROUP BY  is used. This generates a query without.
		excludeTestsMatching 'org.hibernate.orm.test.query.hql.InsertSelectTests.testInsertSelectGroupBy'


        // JIRA DB-40459: Problem with atan2, FIXED in NuoDB 7.0.2
        // Dialect modified to swap arguments in earlier releases.
        // if (nuodbDatabaseVersion.isAfter("7.0.1"))
        //     excludeTestsMatching 'CriteriaBuilderNonStandardFunctionsTest.testAtan2'

        // NuoDB does not use Catalogs
        excludeTestsMatching 'org.hibernate.orm.test.boot.database.qualfiedTableNaming.DefaultCatalogAndSchemaTest'

        // NuoDB does not take read locks
        excludeTestsMatching 'LockTest.testUpdateWithPessimisticReadLockSkipLocked'  
    	//excludeTestsMatching 'FollowOnLockingTest.testQueryLockingWithFollowOn'
    	excludeTestsMatching 'FollowOnLockingTest.testQueryLockingWithoutFollowOn'

        // Functions NuoDB doesn't support
        excludeTestsMatching 'org.hibernate.orm.test.query.criteria.CriteriaBuilderNonStandardFunctionsTest.testLog' // LOG() not supported
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testMathFunctions' // ln() not implemented
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testHexFunction'  // hex() not implemented
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testMedian'  // median() not supported
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.StandardFunctionTests.testLog' // ln() not implemented
        //excludeTestsMatching 'org.hibernate.orm.test.query.hql.StandardFunctionTests.testMathFunctions' // ln() not implemented, test modified to skip it

        // Miscellaneous behaviours NuoDB doesn't support
        excludeTestsMatching 'NamedQueryCommentTest' // our query hints go after select/update not before
		excludeTestsMatching 'NullPrecedenceTest.testNullPrecedence'  // NuoDB does not support NULL precedence

        // Function tests that NuoDB can't support
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testCastBinaryWithLength'  // NuoDB doesn't automatically truncate
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testCastFunction' // NuoDB doesn't automatically truncate. No result found for query [select cast(e.theBoolean as String) from EntityOfBasics e] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testAddSecondsWithFractionalPart' // Loses fractional part

        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testCastStringToBoolean' // SELECT ... UNION  SELECT  without FROM not supported 
                            // select (select v.x from (select true x ^union all select false) v left join (select 't' k,true v union all select 'true',true union all select 'y',true union all select '1',true union all select 'f',false union all select 'false',false union all select 'n',false union all select '0',false) t on lower('1')=t.k where t.v is null or v.x=t.v) FROM Dual 

        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testDateTruncWithOffsetFunction' // Expected: one of {<1974-10-03T00:00-12:00>, <1974-10-04T00:00Z>} but: was <1974-10-03T23:00Z> 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testDurationArithmeticWithLiterals' // Expected: <PT120H> but was: <null> 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testDurationSubtractionWithDatetimeLiterals' // Expected: <PT840H> but was: <null> 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testDurationArithmeticOverflowing'  // Numeric overflow
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testDurationBy' // No result found for query [select e.theDuration from EntityOfBasics e] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testDurationCast' //  No result found for query [select cast(e.theDuration as Long) from EntityOfBasics e] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testDurationLiterals' //  No result found for query [select e.theDuration from EntityOfBasics e] 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testExtractFunctionTimeZone' // SQLGrammar exception unexpected timezone_hour
                                       // select extract(^timezone_hour from eob1_0.the_zoned_date_time) from EntityOfBasics eob1_0 
        //excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testExtractFunctionWithAssertions' // IndexOutOfBounds Index 0 out of bounds for length 0 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.FunctionTests.testExtractOffsetHourMinute' //SQLGrammar JDBC exception
                                       // select extract(^timezone_hour from {ts '2024-02-05 09:18:12.000000000'}) FROM Dual 

        // Expected not <null>.  Was: can't use a DATE as a TIME
        excludeTestsMatching 'org.hibernate.orm.test.temporal.TimePropertyTest'

        // No support for TIMESTAMP_WITH_TIME_ZONE
		excludeTestsMatching 'org.hibernate.orm.test.instant.InstantTest.testStorage'
		excludeTestsMatching 'org.hibernate.orm.test.instant.InstantWithNormalizedTest.test'

        // WITH (a, b, ...) AS (subquery) is illegal syntax
		excludeTestsMatching 'org.hibernate.orm.test.query.CteTests.testInSubquery' // Returns more than one row
		excludeTestsMatching 'org.hibernate.orm.test.query.CteTests.testSubquery'   // emulation -> unsupported SQL construct
        excludeTestsMatching 'org.hibernate.orm.test.hql.HQLTest.test_hql_cte_materialized_example'
        excludeTestsMatching 'org.hibernate.orm.test.jpa.criteria.cte.CriteriaCteCopyTest.testValidRootQuery'
        excludeTestsMatching 'org.hibernate.orm.test.jpa.criteria.cte.CriteriaCteCopyTest.testValidSubQuery'
        excludeTestsMatching 'org.hibernate.orm.test.query.CteTests.testBasic'
        excludeTestsMatching 'org.hibernate.orm.test.query.CteTests.testBasicJoined'
        excludeTestsMatching 'org.hibernate.orm.test.query.CteTests.testMaterialized'
        excludeTestsMatching 'org.hibernate.orm.test.query.CteTests.testNested'
        excludeTestsMatching 'org.hibernate.orm.test.jpa.query.CorrelationCteDerivedJoinTest.tesCte'
        excludeTestsMatching 'org.hibernate.orm.test.jpa.query.CorrelationCteDerivedJoinTest.tesDerivedJoin'
        excludeTestsMatching 'org.hibernate.orm.test.query.criteria.CriteriaCteOffsetFetchTest'
        excludeTestsMatching 'org.hibernate.orm.test.query.criteria.CriteriaCteUnionTest'
        excludeTestsMatching 'org.hibernate.orm.test.subquery.MultipleIdenticalColumnsInSubqueryTest.CTE_with_same_column_selected_twice'
        excludeTestsMatching 'org.hibernate.orm.test.jpa.query.CorrelationCteDerivedRootTest.tesCte'

        // IS [NOT] DISTINCT FROM not supported
        //excludeTestsMatching 'org.hibernate.orm.test.bootstrap.binding.annotations.embedded.EmbeddedTest.testQueryWithEmbeddedParameterOneNull'
        //excludeTestsMatching 'org.hibernate.orm.test.bootstrap.binding.annotations.embedded.EmbeddedTest.testQueryWithEmbeddedParameterAllNull' 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.DistinctFromTest.testNotDistinctFromNullParam'
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.DistinctFromTest.testNotDistinctFromStringParam'
        excludeTestsMatching 'org.hibernate.orm.test.type.VarbinaryArrayTest'
        excludeTestsMatching 'org.hibernate.orm.test.type.BasicListTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.BasicSortedSetTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.BooleanArrayTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.DateArrayTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.DoubleArrayTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.EnumArrayTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.EnumSetConverterTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.EnumSetTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.FloatArrayTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.IntegerArrayTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.LongArrayTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.ShortArrayTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.TimeArrayTest.testQuery'
        excludeTestsMatching 'org.hibernate.orm.test.type.TimestampArrayTest.testQuery'
		excludeTestsMatching 'org.hibernate.orm.test.query.hql.DistinctFromTest'

        // Subqueries in ORDER BY clause
        excludeTestsMatching 'org.hibernate.orm.test.hql.size.filter.WhereAnnotatedOneToManySizeTest.orderBy_sizeOf'
		excludeTestsMatching 'SubqueryOperatorsTest.testSubqueryInVariousClauses'

        // Multi-column value only allowed in comparison operators
        // excludeTestsMatching 'org.hibernate.orm.test.annotations.cid.CompositeIdTest'
        // excludeTestsMatching 'org.hibernate.orm.test.annotations.cid.HierarchicalCompositeIdLazyTest'
        // excludeTestsMatching 'org.hibernate.orm.test.annotations.collectionelement.EmbeddableElementCollectionMemberOfTest'
        // excludeTestsMatching 'org.hibernate.orm.test.annotations.derivedidentities.bidirectional.CompositeIdDerivedIdWithIdClassTest'
        // excludeTestsMatching 'org.hibernate.orm.test.hql.HQLTest.test_hql_in_predicate_example_6'

        // ResultSet is forward-only
        excludeTestsMatching 'org.hibernate.orm.test.hql.ScrollableCollectionFetchingTest.testScrollingJoinFetchesEmptyResultSet'
        excludeTestsMatching 'org.hibernate.orm.test.hql.ScrollableCollectionFetchingTest.testScrollingJoinFetchesPositioning'
        excludeTestsMatching 'org.hibernate.orm.test.hql.ScrollableCollectionFetchingTest.testScrollingJoinFetchesReverse'
        excludeTestsMatching 'org.hibernate.orm.test.hql.ScrollableCollectionFetchingTest.testScrollingJoinFetchesSingleRowResultSet'
        excludeTestsMatching 'org.hibernate.orm.test.jpa.criteria.fetchscroll.CriteriaToScrollableResultsFetchTest.testWithScroll'
        excludeTestsMatching 'org.hibernate.orm.test.resulttransformer.ResultTransformerTest'

        // Scrollable ResultSets not supported
        excludeTestsMatching 'org.hibernate.orm.test.query.sqm.BasicSelectionQueryTests.rawEntitySelectTest'
        excludeTestsMatching 'org.hibernate.orm.test.query.sqm.BasicSelectionQueryTests.rawNamedSelectTest'
        excludeTestsMatching 'org.hibernate.orm.test.query.sqm.BasicSelectionQueryTests.rawScalarSelectTest'
        excludeTestsMatching 'org.hibernate.orm.test.query.sqm.BasicSelectionQueryTests.tupleSelectionTest'
        excludeTestsMatching 'org.hibernate.orm.test.query.sqm.BasicSelectionQueryTests.tupleSelectionTestBaseline'
        excludeTestsMatching 'org.hibernate.orm.test.query.sqm.BasicSelectionQueryTests.typedEntitySelectTest'
        excludeTestsMatching 'org.hibernate.orm.test.query.sqm.BasicSelectionQueryTests.typedScalarSelectTest'
        excludeTestsMatching 'org.hibernate.orm.test.query.sqm.BasicSelectionQueryTests.typesNamedSelectTest'
        excludeTestsMatching 'org.hibernate.orm.test.query.returns.ScrollableResultsTests'
        excludeTestsMatching 'org.hibernate.orm.test.hql.ScrollableCollectionFetchingTest.testScrollingNoJoinFetchesPositioning'

        // CREATE TABLE ... COMMENT not supported, nor is COMMENT ON
        excludeTestsMatching 'org.hibernate.orm.test.schemaupdate.TableCommentTest'

        // Can't get previous value from a sequence
        excludeTestsMatching 'org.hibernate.orm.test.id.SequenceStyleGeneratorBehavesLikeSequeceHiloGeneratorWitZeroIncrementSizeTest'

        // ALL not supported
        excludeTestsMatching 'org.hibernate.orm.test.hql.HQLTest.test_hql_collection_expressions_example_8'
        excludeTestsMatching 'org.hibernate.orm.test.hql.HQLTest.test_hql_all_subquery_comparison_qualifier_example'
		excludeTestsMatching 'org.hibernate.orm.test.query.criteria.SubQueryTests.modifiedSubQueryHqlTest'
		excludeTestsMatching 'org.hibernate.orm.test.query.criteria.SubQueryTests.modifiedSubQueryTest'
        excludeTestsMatching 'org.hibernate.orm.test.jpa.criteria.subquery.UncorrelatedSubqueryTest.testEqualAll'

        // Any(sub-query) not supported, emulation with min/max also fails because sub-query in max/min also not supported 
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.SubqueryOperatorsTest.testAny' // any(sub-query) not supported
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.SubqueryOperatorsTest.testEvery'
        excludeTestsMatching 'org.hibernate.orm.test.hql.HQLTest.test_hql_collection_expressions_example_5' // any(sub-query) not supported

        // Integrity contraints, FKs not enforced
        excludeTestsMatching 'org.hibernate.orm.test.annotations.refcolnames.constraints.OneToManyRefColumnNameTest.testForeignKey'
        excludeTestsMatching 'org.hibernate.orm.test.exception.SQLExceptionConversionTest.testIntegrityViolation'
        excludeTestsMatching 'org.hibernate.orm.test.jpa.exception.ExceptionTest.testConstraintViolationException'

        // Cross JOIN not supported
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.JpaCrossJoinTests.test2Roots'
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.JpaCrossJoinTests.test2Roots2'
        excludeTestsMatching 'org.hibernate.orm.test.query.hql.JpaCrossJoinTests.testCrossJoin'
    }
}
// END: For NUODB

dependencies {
    api jakartaLibs.jpa
    api jakartaLibs.jta

    implementation libs.hibernateModels
    implementation libs.classmate
    implementation libs.byteBuddy

    implementation jakartaLibs.jaxbApi
    implementation jakartaLibs.jaxb
    implementation jakartaLibs.inject

    implementation libs.antlrRuntime

    compileOnly jakartaLibs.jacc
    compileOnly jakartaLibs.validation
    compileOnly jakartaLibs.cdi
    compileOnly jakartaLibs.jsonbApi
    compileOnly libs.jackson
    compileOnly libs.jacksonXml
    compileOnly jdbcLibs.postgresql
    compileOnly jdbcLibs.edb

    testImplementation project(':hibernate-testing')
    testImplementation project(':hibernate-ant')
    testImplementation project(':hibernate-scan-jandex')

    testImplementation testLibs.shrinkwrap
    testImplementation testLibs.shrinkwrapDescriptors
    testImplementation jakartaLibs.cdi
    testImplementation jakartaLibs.jacc
    testImplementation jakartaLibs.validation
    testImplementation( testLibs.validator ) {
        // for test runtime
        transitive = true
    }
    testImplementation "joda-time:joda-time:2.3"
    testImplementation jdbcLibs.h2
    testImplementation libs.hibernateModelsJandex

    testRuntimeOnly libs.byteBuddy
    testRuntimeOnly testLibs.weld
    testRuntimeOnly testLibs.wildFlyTxnClient
    testImplementation libs.jandex
    testImplementation jakartaLibs.jsonb
    testImplementation libs.jackson
    testRuntimeOnly libs.jacksonXml
    testRuntimeOnly libs.jacksonJsr310

    testAnnotationProcessor project( ':hibernate-processor' )

    // NOTE: it seems like, since 4.10, the Antlr Tool no longer defines
    // transitive dep on the corresponding Antlr Runtime.  At least, I get
    // errors about mismatched versions if I do not include the runtime
    // dependency here.
    antlr libs.antlr
    antlr libs.antlrRuntime
}

jar {
    manifest {
        attributes(
                'Main-Class': 'org.hibernate.Version'
        )
    }
}

ext {
    jaxbTargetDir = project.file( "${buildDir}/generated/sources/xjc/main" )
}

sourceSets {
    test {
        resources {
            srcDir 'src/test/resources'
            srcDir 'src/test/bundles'
        }
    }
}

xjc {
    outputDirectory = project.jaxbTargetDir

    schemas {
        cfg {
            xsdFile = 'src/main/resources/org/hibernate/xsd/cfg/legacy-configuration-4.0.xsd'
            xjcBindingFile = 'src/main/xjb/hbm-configuration-bindings.xjb'
        }
        hbm {
            xsdFile = file( 'src/main/resources/org/hibernate/xsd/mapping/legacy-mapping-4.0.xsd' )
            xjcBindingFile = file( 'src/main/xjb/hbm-mapping-bindings.xjb' )
            xjcExtensions += ['inheritance', 'simplify']
        }
        configuration {
            xsdFile = file( 'src/main/resources/org/hibernate/xsd/cfg/configuration-3.2.0.xsd' )
            xjcBindingFile = file( 'src/main/xjb/configuration-bindings.xjb' )
            xjcExtensions += ['inheritance', 'simplify']
        }
        mapping {
            xsdFile = file( 'src/main/resources/org/hibernate/xsd/mapping/mapping-7.0.xsd' )
            xjcBindingFile = file( 'src/main/xjb/mapping-bindings.xjb' )
            xjcExtensions += ['inheritance', 'simplify']
        }
    }
}

task copyBundleResourcesXml (type: Copy) {
    inputs.property( "db", db )
    inputs.property( "dbHost", dbHost )
    ext {
        bundlesTargetDir = file( "${buildDir}/bundles" )
        // Escape
        bundleTokens = [
                'db.dialect' : dbBundle[db]['db.dialect'].replace("&", "&amp;"),
                'jdbc.driver' : dbBundle[db]['jdbc.driver'].replace("&", "&amp;"),
                'jdbc.user' : dbBundle[db]['jdbc.user'].replace("&", "&amp;"),
                'jdbc.pass' : dbBundle[db]['jdbc.pass'].replace("&", "&amp;"),
                'jdbc.url' : dbBundle[db]['jdbc.url'].replace("&", "&amp;"),
                'jdbc.datasource' : dbBundle[db]['jdbc.datasource'].replace("&", "&amp;"),
                'connection.init_sql' : dbBundle[db]['connection.init_sql'].replace("&", "&amp;")
        ]
        ext.bundleTokens['buildDirName'] = project.relativePath( buildDir )
    }

    from('src/test/bundles/templates') {
        include '**/*.xml'
    }
    into ext.bundlesTargetDir
    filter( ReplaceTokens, tokens: ext.bundleTokens)

    doFirst {
        ext.bundlesTargetDir.mkdirs()
    }
}

task copyBundleResourcesNonXml (type: Copy) {
    inputs.property( "db", db )
    ext {
        bundlesTargetDir = file( "${buildDir}/bundles" )
        // Escape
        bundleTokens = dbBundle[db]
        ext.bundleTokens['buildDirName'] = project.relativePath( buildDir )
    }

    from('src/test/bundles/templates') {
        exclude '**/*.xml'
    }
    into ext.bundlesTargetDir
    filter( ReplaceTokens, tokens: ext.bundleTokens)

    doFirst {
        ext.bundlesTargetDir.mkdirs()
    }
}

task copyBundleResources (type: Copy) {
    inputs.property( "db", db )
    dependsOn tasks.copyBundleResourcesXml
    dependsOn tasks.copyBundleResourcesNonXml
}

processTestResources {
    dependsOn copyBundleResources
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

sourcesJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

task testJar(type: Jar, dependsOn: testClasses) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveClassifier.set( 'test' )
    from sourceSets.test.output
}

artifacts {
    tests testJar
}

tasks.register( "generateAnnotationClasses", JavaCompile ) {
    description = "Generate concrete classes for Hibernate and JPA annotations"

    source = sourceSets.main.allJava
    include "org/hibernate/annotations/*"
    classpath = sourceSets.main.runtimeClasspath + sourceSets.main.compileClasspath
    options.annotationProcessorPath = sourceSets.main.compileClasspath
    options.compilerArgs = [
            "-proc:only",
            "-processor",
            "org.hibernate.orm.build.annotations.ClassGeneratorProcessor"
    ]

    destinationDirectory.set( project.layout.buildDirectory.dir( "generated/sources/annotations/" ) )
}

task generateEnversStaticMetamodel(
        type: JavaCompile,
        description: "Generate the Hibernate Envers revision entity static metamodel classes." ) {
    source = sourceSets.main.java
    // we only want to include these specific classes for metamodel generation.
    // if envers adds any additional revision entity classes, they must be listed here.
    include 'org/hibernate/envers/DefaultRevisionEntity.java'
    include 'org/hibernate/envers/DefaultTrackingModifiedEntitiesRevisionEntity.java'
    include 'org/hibernate/envers/enhanced/SequenceIdRevisionEntity.java'
    include 'org/hibernate/envers/enhanced/SequenceIdTrackingModifiedEntitiesRevisionEntity.java'

    classpath = sourceSets.main.runtimeClasspath + sourceSets.test.compileClasspath
    options.compilerArgs = [
            "-proc:only",
            "-processor",
            "org.hibernate.processor.HibernateProcessor"
    ]

    // put static metamodel classes back out to the source tree since they're version controlled.
    destinationDirectory = new File( "${projectDir}/src/main/java" )
}

tasks.withType( Test.class ).each { test ->
    test.systemProperty 'file.encoding', 'utf-8'
    // Allow creating a function in HSQLDB for this Java method
    test.systemProperty 'hsqldb.method_class_names', 'org.hibernate.orm.test.jpa.transaction.TransactionTimeoutTest.sleep'

    // See org.hibernate.boot.model.naming.NamingHelperTest.DefaultCharset.set
    test.jvmArgs( ['--add-opens', 'java.base/java.nio.charset=ALL-UNNAMED'] )
    // Weld needs this to generate proxies
    test.jvmArgs( ['--add-opens', 'java.base/java.security=ALL-UNNAMED'] )
    test.jvmArgs( ['--add-opens', 'java.base/java.lang=ALL-UNNAMED'] )

    //Avoid Log4J2 classloader leaks:
    test.jvmArgs( ['-Dlog4j2.disableJmx=true'] )

    test.beforeTest { descriptor ->
        //println "Starting test: " + descriptor
    }
    if ( project.db == "h2" || project.db == "hsqldb" ) {
        // Parallel test runs when running with in-memory databases
        test.maxParallelForks = Runtime.runtime.availableProcessors().intdiv( 2 ) ?: 1
    }
}

tasks.named( "javadoc", Javadoc ) {
    configure(options) {
        overview = rootProject.file( "shared/javadoc/overview.html" )
        exclude( "**/internal/**", "org/hibernate/boot/jaxb/**", "org/hibernate/tuple/**" )
    }
}

tasks.sourcesJar.dependsOn ':hibernate-core:generateGraphParser'
tasks.sourcesJar.dependsOn ':hibernate-core:generateHqlParser'
tasks.sourcesJar.dependsOn ':hibernate-core:generateSqlScriptParser'
tasks.sourcesJar.dependsOn ':hibernate-core:generateOrderingParser'
